
import type { Product, Supplier, Review, Category, CartItem } from "@/types";

export const placeholderCategories: Category[] = [
  { id: "cat1", name: "Fiber Cables", slug: "fiber-cables", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Simplex-SC-APC-9-125-Single-mode-Fiber-Optic-Pigtail-400x400.jpg" },
  { id: "cat2", name: "Connectors", slug: "connectors", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Fast_connector_SC_APC-removebg-preview-1.png" },
  { id: "cat3", name: "Adapters", slug: "adapters", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/1_e82d820a-ede1-4d97-8bd4-a39a657ff22b-400x400.webp" },
  { id: "cat4", name: "Patch Panels", slug: "patch-panels", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/atb-with-2pcs-Lc-upc-pigtails-and-2pcs-lc-upc-duplex-adapter-400x202.png" }, // Using ATB image
  { id: "cat5", name: "Networking Tools", slug: "networking-tools", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/10/fibertool-kit-400x400.jpg" },
  { id: "cat6", name: "SFP Modules", slug: "sfp-modules", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/BARE-SPLITTER-0.5MM-1-400x350.png" }, // Using Bare Splitter image
  { id: "cat7", name: "Media Converters", slug: "media-converters", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/atb-with-2pcs-Lc-upc-pigtails-and-2pcs-lc-upc-duplex-adapter-400x202.png" }, // Using ATB image
  { id: "cat8", name: "Cable Management", slug: "cable-management", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/ADSS-J-Hook-400x400.jpg" },
  { id: "cat9", name: "Testers", slug: "testers", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Splicing-Machine-AI-9-Signal-Fire-400x400.jpg" }, // Using Splicing Machine image
  { id: "cat10", name: "Enclosures", slug: "enclosures", imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/atb-with-2pcs-Lc-upc-pigtails-and-2pcs-lc-upc-duplex-adapter-400x202.png" } // Using ATB image
];

export const placeholderReviews: Review[] = [
  { id: "rev1", author: "Alice Smith", rating: 5, comment: "Excellent SC/APC connector, very high quality!", date: "2023-05-15T10:00:00Z", productId: "prod1", avatarUrl: "https://placehold.co/40x40.png?user=alice" },
  { id: "rev2", author: "Bob Johnson", rating: 4, comment: "Good value for this fast connector.", date: "2023-05-20T14:30:00Z", productId: "prod1", avatarUrl: "https://placehold.co/40x40.png?user=bob" },
  { id: "rev3", author: "Carol Williams", rating: 3, comment: "Decent pigtail, but a bit stiff.", date: "2023-06-01T09:15:00Z", productId: "prod2", avatarUrl: "https://placehold.co/40x40.png?user=carol" },
  { id: "rev4", author: "David Brown", rating: 5, comment: "Supplier was very helpful and shipping was fast.", date: "2023-06-05T11:00:00Z", supplierId: "sup1", avatarUrl: "https://placehold.co/40x40.png?user=david" },
  { id: "rev5", author: "Eve Davis", rating: 2, comment: "This SC/APC connector (Type B) didn't fit well.", date: "2023-06-10T16:45:00Z", productId: "prod3", avatarUrl: "https://placehold.co/40x40.png?user=eve" },
];

export const placeholderProducts: Product[] = [
  {
    id: "prod1",
    name: "SC/APC Fast Connector",
    description: "High-quality SC/APC fast connector for quick fiber optic termination.",
    longDescription: "This SC/APC fast connector allows for easy and quick termination of fiber optic cables in the field. No polishing or epoxy required. Ideal for FTTx applications, data centers, and LAN. Features low insertion loss and high return loss.",
    price: 50,
    category: "Connectors",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Fast_connector_SC_APC-removebg-preview-1.png",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Fast_connector_SC_APC-removebg-preview-1.png"],
    stock: 480,
    rating: 4.5,
    reviewCount: 2,
    reviews: placeholderReviews.filter(r => r.productId === "prod1"),
    brand: "FiberLink",
    specifications: { "Connector Type": "SC/APC", "Application": "FTTx, LAN", "Insertion Loss": "<0.3dB", "Return Loss": ">60dB" }
  },
  {
    id: "prod2",
    name: "Simplex SC/APC Single Mode Pigtail",
    description: "9/125 Single mode simplex fiber optic pigtail with SC/APC connector.",
    longDescription: "High-quality simplex SC/APC single mode (9/125µm) fiber optic pigtail. Ideal for splicing applications in ODF, patch panels, and fiber optic distribution frames. Standard 0.9mm buffer diameter.",
    price: 50,
    category: "Fiber Cables",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Simplex-SC-APC-9-125-Single-mode-Fiber-Optic-Pigtail-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Simplex-SC-APC-9-125-Single-mode-Fiber-Optic-Pigtail-400x400.jpg"],
    stock: 250,
    rating: 3.0,
    reviewCount: 1,
    reviews: placeholderReviews.filter(r => r.productId === "prod2"),
    brand: "CoreOptics",
    specifications: { "Connector": "SC/APC", "Fiber Type": "Single Mode G.657.A1", "Buffer Diameter": "0.9mm", "Length": "1.5m" }
  },
  {
    id: "prod3",
    name: "Fiber SC/APC Fast Connector (Type B)",
    description: "Alternative SC/APC fast connector for reliable fiber termination.",
    longDescription: "This Type B SC/APC fast connector provides a robust and quick solution for field fiber termination. Suitable for drop cables and indoor fiber installations. Ensures stable optical performance.",
    price: 50,
    category: "Connectors",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Fiber-SC-APC-Fast-Connector-400x321.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Fiber-SC-APC-Fast-Connector-400x321.jpg"],
    stock: 300,
    rating: 2.0,
    reviewCount: 1,
    reviews: placeholderReviews.filter(r => r.productId === "prod3"),
    brand: "FiberLink",
    specifications: { "Connector Style": "SC/APC Type B", "Durability": ">500 matings", "Operating Temp": "-40°C to +75°C" }
  },
  {
    id: "prod4",
    name: "Outdoor Drop Cable (2km Spool)",
    description: "Durable outdoor fiber optic drop cable, 2km length.",
    longDescription: "Self-supporting outdoor drop cable designed for aerial and duct installations. Features a robust construction to withstand harsh environmental conditions. Ideal for last-mile FTTx connectivity. Sold per 2km spool.",
    price: 11000,
    category: "Fiber Cables",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/10/drop-cable-2km-400x352.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/10/drop-cable-2km-400x352.jpg"],
    stock: 30,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "DuraSpan",
    specifications: { "Length": "2km", "Type": "Self-supporting, Outdoor", "Fiber Count": "1-4 Cores Available", "Tensile Strength": "High" }
  },
  {
    id: "prod5",
    name: "Access Terminal Box (ATB) - LC/UPC",
    description: "Compact ATB with 2 LC/UPC pigtails and 2 LC/UPC duplex adapters.",
    longDescription: "This Access Terminal Box is designed for FTTx applications, providing a compact solution for terminating and distributing optical fibers. Comes pre-loaded with 2 LC/UPC pigtails and 2 LC/UPC duplex adapters.",
    price: 140,
    category: "Enclosures",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/atb-with-2pcs-Lc-upc-pigtails-and-2pcs-lc-upc-duplex-adapter-400x202.png",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/08/atb-with-2pcs-Lc-upc-pigtails-and-2pcs-lc-upc-duplex-adapter-400x202.png"],
    stock: 120,
    rating: 4.2,
    reviewCount: 0,
    reviews: [],
    brand: "TermiBox",
    specifications: { "Capacity": "2 Fibers", "Adapters": "2x LC/UPC Duplex", "Pigtails": "2x LC/UPC", "Material": "ABS Plastic" }
  },
  {
    id: "prod6",
    name: "LC/UPC to SC/UPC Patch Cord",
    description: "Fiber optic patch cord, LC/UPC to SC/UPC connectors, simplex/duplex.",
    longDescription: "High-quality fiber optic patch cord for connecting network devices. Features LC/UPC on one end and SC/UPC on the other. Available in simplex or duplex configurations and various lengths.",
    price: 150,
    category: "Fiber Cables",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/fibre-patch-cord-lc-upc-sc-upc-400x328.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/fibre-patch-cord-lc-upc-sc-upc-400x328.jpg"],
    stock: 350,
    rating: 4.6,
    reviewCount: 0,
    reviews: [],
    brand: "PatchLink",
    specifications: { "Connector A": "LC/UPC", "Connector B": "SC/UPC", "Mode": "Single Mode / Multi Mode", "Length": "1m, 3m, 5m" }
  },
  {
    id: "prod7",
    name: "ADSS J-Hook Cable Support",
    description: "Durable J-Hook for supporting ADSS and other outdoor cables.",
    longDescription: "ADSS J-Hook designed for suspending aerial fiber optic cables. Made from high-strength, UV-resistant material for long-term outdoor use. Provides secure and organized cable routing.",
    price: 330,
    category: "Cable Management",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/ADSS-J-Hook-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/08/ADSS-J-Hook-400x400.jpg"],
    stock: 1000,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "CableHold",
    specifications: { "Material": "UV-Resistant Polymer/Metal", "Application": "Aerial Cable Suspension", "Cable Diameter": "Up to 20mm" }
  },
  {
    id: "prod8",
    name: "AI-9 Signal Fire Splicing Machine",
    description: "Advanced automatic optical fiber fusion splicer.",
    longDescription: "The Signal Fire AI-9 is a fully automatic, core-alignment fusion splicer. Features fast splicing and heating times, a rugged design for field use, and a high-resolution LCD screen. Comes with a complete toolkit.",
    price: 80000,
    category: "Networking Tools",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Splicing-Machine-AI-9-Signal-Fire-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Splicing-Machine-AI-9-Signal-Fire-400x400.jpg"],
    stock: 15,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Signal Fire",
    specifications: { "Model": "AI-9", "Alignment": "Core Alignment", "Splicing Time": "6s", "Heating Time": "15s" }
  },
  {
    id: "prod9",
    name: "Simplex SC/UPC Single Mode Pigtail",
    description: "Standard SC/UPC single mode simplex fiber optic pigtail.",
    longDescription: "Reliable simplex SC/UPC single mode fiber optic pigtail for various telecommunication applications. Features low insertion loss and excellent durability. Suitable for fusion splicing.",
    price: 50,
    category: "Fiber Cables",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Simplex-SC-UPC-Single-Mode-Fiber-Optic-Pigtail-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/Simplex-SC-UPC-Single-Mode-Fiber-Optic-Pigtail-400x400.jpg"],
    stock: 280,
    rating: 4.3,
    reviewCount: 0,
    reviews: [],
    brand: "CoreOptics",
    specifications: { "Connector": "SC/UPC", "Fiber Type": "Single Mode G.652.D", "Buffer Diameter": "0.9mm", "Length": "1m" }
  },
  {
    id: "prod10",
    name: "Fiber Optic Tool Kit",
    description: "Comprehensive tool kit for fiber optic installation and maintenance.",
    longDescription: "This complete fiber optic tool kit includes essentials like fiber cleaver, stripper, power meter, visual fault locator, and various cleaning supplies. Packaged in a durable carrying case.",
    price: 6000,
    category: "Networking Tools",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/10/fibertool-kit-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/10/fibertool-kit-400x400.jpg"],
    stock: 40,
    rating: 4.5,
    reviewCount: 0,
    reviews: [],
    brand: "ProKit",
    specifications: { "Key Tools": "Cleaver, Power Meter, VFL", "Case": "Durable Carrying Case", "Application": "Installation, Maintenance" }
  },
  {
    id: "prod11",
    name: "Laser Pen",
    description: "SC/UPC to SC/UPC duplex fiber optic adapter.",
    longDescription: "High-precision SC/UPC duplex adapter for connecting two SC/UPC duplex fiber optic patch cords. Features low insertion loss and a durable housing for reliable connections.",
    price: 3500,
    category: "Adapters",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/1_e82d820a-ede1-4d97-8bd4-a39a657ff22b-400x400.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/07/1_e82d820a-ede1-4d97-8bd4-a39a657ff22b-400x400.webp"],
    stock: 600,
    rating: 4.4,
    reviewCount: 0,
    reviews: [],
    brand: "AdaptLink",
    specifications: { "Type": "SC/UPC Duplex", "Sleeve Material": "Ceramic", "Insertion Loss": "<0.2dB" }
  },
  {
    id: "prod12",
    name: "Universal Pole Bracket (UPB)",
    description: "Versatile universal pole bracket for mounting telecom equipment.",
    longDescription: "The Universal Pole Bracket (UPB) is designed for easy and secure mounting of various telecommunication equipment on poles. Made from galvanized steel for corrosion resistance.",
    price: 200,
    category: "Cable Management",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/08/Universal-Pole-Bracket-UPB-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/08/Universal-Pole-Bracket-UPB-400x400.jpg"],
    stock: 90,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "MountPro",
    specifications: { "Material": "Galvanized Steel", "Application": "Pole Mounting", "Compatibility": "Universal" }
  },
  {
    id: "prod13",
    name: "Bare Fiber PLC Splitter 1x4",
    description: "1x4 bare fiber PLC splitter for optical signal distribution.",
    longDescription: "This 1x4 Planar Lightwave Circuit (PLC) splitter divides a single optical input into four outputs with minimal loss. Bare fiber type for integration into custom enclosures or splice trays.",
    price: 250,
    category: "SFP Modules",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2021/07/BARE-SPLITTER-0.5MM-1-400x350.png",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2021/07/BARE-SPLITTER-0.5MM-1-400x350.png"],
    stock: 70,
    rating: 4.1,
    reviewCount: 0,
    reviews: [],
    brand: "SplitOptic",
    specifications: { "Type": "PLC Splitter", "Ratio": "1x4", "Fiber Type": "Bare Fiber", "Operating Wavelength": "1260-1650nm" }
  },
  {
    id: "prod14",
    name: "TENDA 5 PORT ETHERNET SWITCH (S105)",
    description: "A simple and reliable 5-port ethernet switch for home and small office use.",
    longDescription: "The Tenda S105 is a 5-port 10/100Mbps Fast Ethernet Switch that provides a simple and affordable way to expand your wired network. It's easy to use, with a plug-and-play design.",
    price: 800,
    category: "Network Switches",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2025/01/tenda-5-port-Photoroom-400x400.png",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2025/01/tenda-5-port-Photoroom-400x400.png"],
    stock: 150,
    rating: 4.5,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Ports": "5 x 10/100Mbps", "Standard": "IEEE 802.3, IEEE 802.3u, IEEE 802.3x" }
  },
  {
    id: "prod15",
    name: "Tenda N301 Wireless N300 Easy Setup Router",
    description: "User-friendly N300 wireless router, perfect for everyday internet activities.",
    longDescription: "The Tenda N301 Wireless N300 Easy Setup Router is designed for easier setup. It complies with IEEE802.11n, delivering wireless speeds of up to 300 Mbps, making it perfect for everyday web activities like email, chatting, streaming videos, online gaming, and more.",
    price: 1300,
    category: "Routers",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/20154111119587310-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/07/20154111119587310-400x400.jpg"],
    stock: 100,
    rating: 4.3,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Speed": "300Mbps", "Antennas": "2 x 5dBi", "Frequency": "2.4GHz" }
  },
  {
    id: "prod16",
    name: "Tenda CP3 Pro 2K Security Camera",
    description: "2K super HD security camera with pan/tilt and AI human detection.",
    longDescription: "The Tenda CP3 Pro is a high-performance home surveillance pan/tilt camera that integrates 2K resolution video, full-duplex two-way audio, smart-motion detection, and auto-tracking functions. ",
    price: 2500,
    category: "Security Cameras",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/20230906141237_6723-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/07/20230906141237_6723-400x400.jpg"],
    stock: 80,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Resolution": "2K (2304x1296)", "Night Vision": "Yes", "Audio": "Two-way" }
  },
  {
    id: "prod17",
    name: "Tenda S108 8-Port Ethernet Switch",
    description: "An 8-port Fast Ethernet switch for expanding your home or office network.",
    longDescription: "The Tenda S108 is an 8-port Fast Ethernet desktop switch that offers a simple solution for expanding your network. It features a plug-and-play design and a compact, desktop-friendly case.",
    price: 1000,
    category: "Network Switches",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/Tenda_S108_Desktop_Switch-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/07/Tenda_S108_Desktop_Switch-400x400.jpg"],
    stock: 120,
    rating: 4.6,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Ports": "8 x 10/100Mbps", "MAC Address Table": "1K" }
  },
  {
    id: "prod18",
    name: "Tenda 4G03 PRO 3G/4G LTE N300 Wi-Fi Router",
    description: "4G LTE router providing Wi-Fi access wherever there is mobile coverage.",
    longDescription: "With LTE advanced signal coverage for best performance and allows you to receive Internet access without cable and fiber, it is the ideal choice for remote areas such as rural and suburban, temporary store, holiday home, giving devices ability to access to the Internet wherever and whenever the user is located.",
    price: 2000,
    category: "Routers",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-20-at-3.35.39-PM-Photoroom-400x400.png",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-20-at-3.35.39-PM-Photoroom-400x400.png"],
    stock: 60,
    rating: 4.4,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Network Type": "3G/4G LTE", "Wi-Fi Speed": "N300", "SIM Card Slot": "Yes" }
  },
  {
    id: "prod19",
    name: "Tenda T10 N300 Wi-Fi Range Extender",
    description: "Boost your Wi-Fi signal to eliminate dead zones in your home.",
    longDescription: "The Tenda T10 is a 300Mbps Wi-Fi range extender that helps to expand your existing Wi-Fi coverage. With its wall-plug design and smart signal indicator, it's easy to find the perfect location to extend your network.",
    price: 2000,
    category: "Range Extenders",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/07/N300-1-400x400.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/07/N300-1-400x400.webp"],
    stock: 95,
    rating: 4.2,
    reviewCount: 0,
    reviews: [],
    brand: "Tenda",
    specifications: { "Speed": "300Mbps", "Frequency": "2.4GHz", "Antennas": "External" }
  },
  {
    id: "prod20",
    name: "Ubiquiti UniFi U6-Enterprise",
    description: "High-performance WiFi 6E access point for enterprise networks.",
    longDescription: "The Ubiquiti UniFi U6-Enterprise is a next-generation, tri-band WiFi 6E access point designed for demanding, high-density enterprise environments. It delivers aggregate, over-the-air speeds of up to 10.2 Gbps with its 5 GHz and 6 GHz bands.",
    price: 32000,
    category: "Wireless Access Points",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/06/Ubiquiti-UniFi-Access-Point-WiFi-6-Pro-U6-PRO-kenya-400x400.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/06/Ubiquiti-UniFi-Access-Point-WiFi-6-Pro-U6-PRO-kenya-400x400.webp"],
    stock: 50,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "WiFi Standard": "Wi-Fi 6E", "Speed": "10.2 Gbps", "Bands": "2.4/5/6 GHz" }
  },
  {
    id: "prod21",
    name: "Ubiquiti 16 Port Switch (USW-Lite-16-POE)",
    description: "A 16-port, Layer 2 PoE switch for enterprise networks.",
    longDescription: "The USW-Lite-16-POE is a fully managed, Layer 2 switch with sixteen Gigabit Ethernet ports, including eight auto-sensing 802.3at PoE+ ports. It provides Gigabit PoE links to your RJ45 Ethernet devices.",
    price: 36000,
    category: "Network Switches",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/11/USW-16-LITE-POE-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/11/USW-16-LITE-POE-400x400.jpg"],
    stock: 40,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Ports": "16 x GbE RJ45", "PoE Ports": "8 x PoE+", "Management": "Layer 2" }
  },
  {
    id: "prod22",
    name: "Ubiquiti UniFi U7 Pro Wall Access Point",
    description: "Next-gen WiFi 7 access point with a sleek, wall-mountable design.",
    longDescription: "The Ubiquiti UniFi U7 Pro Wall is a WiFi 7 access point that brings next-generation wireless performance to any space. It features a sleek, wall-mountable design and delivers blazing-fast speeds for demanding applications.",
    price: 35000,
    category: "Wireless Access Points",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2025/01/U7-PRO-WALL.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2025/01/U7-PRO-WALL.webp"],
    stock: 30,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "WiFi Standard": "Wi-Fi 7", "Mounting": "Wall/Ceiling", "Speed": "Up to 9.3 Gbps" }
  },
  {
    id: "prod23",
    name: "Ubiquiti PowerBeam PBE-5AC-620",
    description: "High-performance airMAX ac bridge for long-range links.",
    longDescription: "The PowerBeam 5AC 620 is an airMAX ac bridge that is ideal for CPE deployments requiring maximum performance. It features a dish reflector design with proprietary airMAX ac technology, providing excellent beam directivity.",
    price: 30000,
    category: "Point to point",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Powerbeam-M5-AC-620-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Powerbeam-M5-AC-620-400x400.jpg"],
    stock: 25,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Frequency": "5 GHz", "Gain": "29 dBi", "Range": "30+ km" }
  },
  {
    id: "prod24",
    name: "Ubiquiti UniFi Cloudkey Gen2 Plus",
    description: "Integrated UniFi controller and NVR with a 1TB HDD.",
    longDescription: "The UniFi Cloud Key Gen2 Plus is a compact, powerful solution for managing your UniFi networks and video surveillance. It features an eight-core processor with 3 GB RAM, a 1 TB SATA HDD for video storage, and supports the UniFi Protect software.",
    price: 27000,
    category: "Network Management",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2020/07/CLOUDKEY-GEN-2-PLUS-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2020/07/CLOUDKEY-GEN-2-PLUS-400x400.jpg"],
    stock: 35,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Storage": "1 TB HDD (Upgradable)", "UniFi Controller": "Included", "UniFi Protect": "Included" }
  },
  {
    id: "prod25",
    name: "UniFi 8 POE Switch (USW-Lite-8-POE)",
    description: "Compact, 8-port Gigabit switch with 4 PoE+ ports.",
    longDescription: "The USW-Lite-8-POE is a fully managed Layer 2 switch with eight Gigabit Ethernet ports. Four ports offer auto-sensing 802.3at PoE+ that provide up to a total PoE wattage of 52W for UniFi Access Points or other PoE devices.",
    price: 12000,
    category: "Network Switches",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2025/03/USW-8-POE-SWITCH.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2025/03/USW-8-POE-SWITCH.jpg"],
    stock: 60,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Ports": "8 x GbE RJ45", "PoE Ports": "4 x PoE+", "Total PoE Wattage": "52W" }
  },
  {
    id: "prod26",
    name: "Ubiquiti U6 Mesh Wireless Access Point",
    description: "Wi-Fi 6 Mesh Outdoor Access Point.",
    longDescription: "The Ubiquiti Networks U6 Mesh is a high-performance, four-stream WiFi 6 access point that brings best-in-class signal meshing to enhance the wireless coverage of home and enterprise networks. It has a sleek, compact design that can be mounted anywhere.",
    price: 12500,
    category: "Wireless Access Points",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2024/06/Ubiquiti-Networks-U6-Mesh-Wireless-Dual-Band-Wi-Fi-6-Mesh-Outdoor-Access-Point-400x400.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2024/06/Ubiquiti-Networks-U6-Mesh-Wireless-Dual-Band-Wi-Fi-6-Mesh-Outdoor-Access-Point-400x400.webp"],
    stock: 70,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "WiFi Standard": "Wi-Fi 6", "MIMO": "4x4", "Weatherproof": "IPX5" }
  },
  {
    id: "prod27",
    name: "Ubiquiti UniFi 6 In-Wall Access Point (U6-IW)",
    description: "Wall-mounted WiFi 6 access point with a built-in PoE switch.",
    longDescription: "The UniFi 6 In-Wall (U6-IW) is a dual-band, wall-mounted WiFi 6 access point that brings next-generation wireless to any space. With its built-in PoE switch, the U6-IW can also provide a wired connection to your devices.",
    price: 18000,
    category: "Wireless Access Points",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2025/03/U6-INWALL.webp",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2025/03/U6-INWALL.webp"],
    stock: 55,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "WiFi Standard": "Wi-Fi 6", "PoE Switch": "4-port GbE", "Mounting": "In-Wall" }
  },
  {
    id: "prod28",
    name: "Ubiquiti airFiber X Antenna (AF-5G30-S45)",
    description: "30dBi slant 45 antenna for airFiber X.",
    longDescription: "The airFiber X Antenna AF-5G30-S45 is a high-gain dish antenna designed for use with the airFiber X radio. It delivers 30 dBi of gain in a 650-mm diameter size and features a slant 45 polarization for improved noise immunity.",
    price: 20000,
    category: "Antennas",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2020/11/Ubiquiti-airFiber-X-Antenna-AF-5G30-S45-30dBi-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2020/11/Ubiquiti-airFiber-X-Antenna-AF-5G30-S45-30dBi-400x400.jpg"],
    stock: 20,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "30 dBi", "Frequency": "5 GHz", "Polarization": "Slant 45" }
  },
  {
    id: "prod29",
    name: "Ubiquiti airMAX Sector Antenna 19dBi 120°",
    description: "5GHz airMAX 2x2 MIMO Sector Antenna.",
    longDescription: "The airMAX Sector Antenna is a Carrier Class 2x2 Dual Polarity MIMO Sector Antenna that was designed to seamlessly integrate with Rocket M5 radios. It features a 19dBi gain and 120° beamwidth.",
    price: 13000,
    category: "Antennas",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-5GHZ-MIMOSECTOR-AIRMAX-120-19DBI.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-5GHZ-MIMOSECTOR-AIRMAX-120-19DBI.jpg"],
    stock: 30,
    rating: 4.6,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "19 dBi", "Beamwidth": "120 deg", "Frequency": "5 GHz" }
  },
  {
    id: "prod30",
    name: "Ubiquiti Rocket AC Lite (R5AC-Lite)",
    description: "High-performance airMAX ac BaseStation.",
    longDescription: "The Rocket AC Lite is a high-performance airMAX ac BaseStation for Point-to-MultiPoint (PtMP) networks. It features proprietary airMAX ac technology for high throughput and low latency in unlicensed 5 GHz networks.",
    price: 12000,
    category: "Wireless Outdoor CPE",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Rocket-AC-Lite.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Rocket-AC-Lite.jpg"],
    stock: 45,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Model": "R5AC-Lite", "Frequency": "5 GHz", "Throughput": "500+ Mbps" }
  },
  {
    id: "prod31",
    name: "Ubiquiti LiteAP AC Sector Antenna",
    description: "Lightweight airMAX ac Access Point with LiteAP technology.",
    longDescription: "The LiteAP ac is an ultra-lightweight airMAX ac Access Point with a 120° sector antenna. It provides a cost-effective and disruptive solution for broadband wireless networking.",
    price: 9500,
    category: "Antennas",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2020/11/Ubiquiti-Lite-AP-GPS-Sector-Antenna-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2020/11/Ubiquiti-Lite-AP-GPS-Sector-Antenna-400x400.jpg"],
    stock: 35,
    rating: 4.5,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "16 dBi", "Beamwidth": "120 deg", "GPS Sync": "Yes" }
  },
  {
    id: "prod32",
    name: "Ubiquiti LiteBeam AC 16dBi 120° AP (LBE-5AC-16-120)",
    description: "airMAX ac CPE with an integrated 120° antenna.",
    longDescription: "The LiteBeam AC AP is an ultra-lightweight airMAX ac Access Point with incredible performance and disruptive pricing. It features a 16dBi antenna with a 120° beamwidth for expanded coverage.",
    price: 15000,
    category: "Wireless Access Points",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/Ubiquiti-LBE-5ac-16-120-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/Ubiquiti-LBE-5ac-16-120-400x400.jpg"],
    stock: 50,
    rating: 4.6,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "16 dBi", "Beamwidth": "120 deg", "Frequency": "5 GHz" }
  },
  {
    id: "prod33",
    name: "Ubiquiti PowerBeam M5 400 (PBE-M5-400)",
    description: "High-performance airMAX bridge for long-range connectivity.",
    longDescription: "The PowerBeam M5 400 directs RF energy in a tighter beamwidth, and its integrated isolator design improves RF isolation to spatially filter out interference. This makes it excellent for long-range links.",
    price: 9500,
    category: "Point to point",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Powerbeam-M5-400-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-Powerbeam-M5-400-400x400.jpg"],
    stock: 40,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "25 dBi", "Frequency": "5 GHz", "Dish Reflector": "400 mm" }
  },
  {
    id: "prod34",
    name: "Ubiquiti LiteBeam AC Gen2 (LBE-5AC-GEN2)",
    description: "airMAX ac CPE with dedicated management Wi-Fi.",
    longDescription: "The LiteBeam AC Gen2 is an ultra-lightweight airMAX ac CPE device with incredibly long range and disruptive pricing. It features a dedicated Wi-Fi radio for easy setup via the UMobile App.",
    price: 9500,
    category: "Wireless Outdoor CPE",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-LITEBEASM-AC-Gen2-23DBI.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-LITEBEASM-AC-Gen2-23DBI.jpg"],
    stock: 65,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "23 dBi", "Management": "Wi-Fi Radio / UMobile App", "Frequency": "5 GHz" }
  },
  {
    id: "prod35",
    name: "Ubiquiti NanoStation Loco M5",
    description: "Compact and cost-effective airMAX CPE.",
    longDescription: "The NanoStation Loco M5 is a compact, high-performance airMAX CPE (Customer Premises Equipment). Featuring a panel antenna and dual-polarity performance, it is ideal for Point-to-MultiPoint (PtMP) applications requiring a sleek form factor.",
    price: 9500,
    category: "Wireless Outdoor CPE",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/10/Ubiquiti-Networks-NanoStation-locoM5-airMAX-CPE-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/10/Ubiquiti-Networks-NanoStation-locoM5-airMAX-CPE-400x400.jpg"],
    stock: 80,
    rating: 4.6,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "13 dBi", "Frequency": "5 GHz", "Form Factor": "Compact" }
  },
  {
    id: "prod36",
    name: "Ubiquiti LiteBeam M5 23dBi (LBE-M5-23)",
    description: "Long-range airMAX CPE for point-to-point and point-to-multipoint links.",
    longDescription: "The LiteBeam M5 is an ultra-lightweight airMAX CPE device. Its combination of a high-gain antenna and InnerFeed technology provides a simple, yet extremely powerful and robust wireless CPE device.",
    price: 2300,
    category: "Wireless Outdoor CPE",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/ubiquiti-litebeam-m5-23dbi-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/ubiquiti-litebeam-m5-23dbi-400x400.jpg"],
    stock: 75,
    rating: 4.7,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Gain": "23 dBi", "Frequency": "5 GHz", "Technology": "airMAX" }
  },
  {
    id: "prod37",
    name: "Ubiquiti PoE Injector, 48V, 0.5A",
    description: "48VDC 0.5A Gigabit PoE injector for Ubiquiti devices.",
    longDescription: "This PoE injector provides 48VDC at 0.5A to power Ubiquiti devices. It offers earth grounding/ESD protection and is compatible with Gigabit LAN ports.",
    price: 1800,
    category: "POE Injectors",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-POE-Injector-48V-0.5A.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-POE-Injector-48V-0.5A.jpg"],
    stock: 200,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Output": "48VDC @ 0.5A", "Gigabit": "Yes", "Model": "POE-48-24W-G" }
  },
  {
    id: "prod38",
    name: "Ubiquiti Ethernet Surge Protector Gen 2",
    description: "Advanced surge protection for outdoor high-speed networks.",
    longDescription: "The ETH-SP-G2 is a cost-effective solution for protecting outdoor Ethernet devices from damaging electrostatic discharge and surges. It features two surge-protected RJ45 ports and is designed for easy, plug-and-play installation.",
    price: 2000,
    category: "Network Accessories",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2020/07/Ubiquiti-Ethernet-Surge-Protector-Gen-2-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2020/07/Ubiquiti-Ethernet-Surge-Protector-Gen-2-400x400.jpg"],
    stock: 150,
    rating: 4.8,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Ports": "2 x RJ45", "Protection": "ESD/EMP", "Model": "ETH-SP-G2" }
  },
  {
    id: "prod39",
    name: "Ubiquiti PoE Injector, 24V, 0.5A",
    description: "24VDC 0.5A PoE injector for Ubiquiti airMAX devices.",
    longDescription: "This PoE adapter provides 24VDC at 0.5A to power various Ubiquiti airMAX devices. It offers protection against surge, clamping, maximum surge discharge, and peak pulse current.",
    price: 2000,
    category: "POE Injectors",
    imageUrl: "https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-POE-Injector-24V-0.5A-400x400.jpg",
    images: ["https://ctcsolutions.co.ke/wp-content/uploads/2018/12/UBNT-POE-Injector-24V-0.5A-400x400.jpg"],
    stock: 250,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    brand: "Ubiquiti",
    specifications: { "Output": "24VDC @ 0.5A", "Model": "POE-24-12W-G" }
  }
];

export const placeholderSuppliers: Supplier[] = [
  {
    id: "sup1",
    name: "OptiConnect Solutions",
    description: "Leading provider of high-quality fiber optic components and solutions for telecommunications and data centers.",
    logoUrl: "https://placehold.co/150x150.png?text=OptiConnect+Logo",
    bannerUrl: "https://placehold.co/1200x300.png?text=OptiConnect+Banner",
    contactEmail: "sales@opticonnect.com",
    website: "https://opticonnect.com",
    rating: 4.2,
    reviewCount: 1,
    reviews: placeholderReviews.filter(r => r.supplierId === "sup1"),
    isVerified: true, // OptiConnect is now a verified supplier
  },
  {
    id: "sup2",
    name: "NetBuild Essentials",
    description: "Your trusted source for networking tools, equipment, and accessories for professionals and DIYers.",
    logoUrl: "https://placehold.co/150x150.png?text=NetBuild+Logo",
    bannerUrl: "https://placehold.co/1200x300.png?text=NetBuild+Banner",
    contactEmail: "info@netbuild.com",
    website: "https://netbuild.com",
    rating: 4.0,
    reviewCount: 0,
    reviews: [],
    isVerified: false,
  },
];

export const placeholderCartItems: CartItem[] = [];

export function getProductById(id: string): Product | undefined {
  return placeholderProducts.find(p => p.id === id);
}

export function getSupplierById(id: string): Supplier | undefined {
  return placeholderSuppliers.find(s => s.id === id);
}

export function getProductsBySupplierId(supplierId: string): Product[] {
  return placeholderProducts.filter(p => p.brand === "Ubiquiti");
}

export function getAllSuppliers(): Supplier[] {
  return placeholderSuppliers;
}
